            name: CI Full Tests

            on:
              workflow_dispatch:
              push:
                branches:
                  - 'main'
                  - 'CI/CD-task'
                  - 'CI/CD-Task'
              pull_request:
                branches:
                  - 'main'

            permissions:
                contents: read
                pages: write
                id-token: write
                  
            concurrency:
                group: 'pages'
                cancel-in-progress: true
              

            jobs:
              build:
                timeout-minutes: 10
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    node-version:
                      - '18.x'
                steps:
                  - name: Checkout repository
                    uses: actions/checkout@v3

                  - name: Use Node.js ${{ matrix.node-version }}
                    uses: actions/setup-node@v3
                    with:
                      node-version: ${{ matrix.node-version }}
                      cache: 'npm'

                  - name: Install dependencies
                    run: npm ci

                  - name: Build package
                    run: npm run build --if-present

                  - name: Run tests
                    run: npm run test

                  - name: Upload report
                    uses: actions/upload-artifact@v3
                    with:
                      name: report
                      if-no-files-found: error
                      path: ./reports/html-report

                  - name: Send telegram message on push
                    uses: appleboy/telegram-action@master
                    with:
                      to: ${{ secrets.TELEGRAM_CHAT_ID }}
                      token: ${{ secrets.TELEGRAM_TOKEN }}
                      message: |
                        ${{ github.actor }} created commit:
                        Commit message: ${{ github.event.commits[0].message }}
                        Repository: ${{ github.repository }}
                        See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

                  - name: Deploy to Github
                    id: deployment
                    uses: action-deploy-page@v3
